[colors.primary]
background = "#010101"
foreground = "#bfbfbf"

[colors.cursor]
text = "#010101"
cursor = "#bfbfbf"

[colors.vi_mode_cursor]
text = "#010101"
cursor = "#bfbfbf"

[colors.search.matches]
foreground = "#010101"
background = "#bfbfbf"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#615050"
background = "#bfbfbf"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#010101"
red = "#EE1F25"
green = "#CD3E46"
yellow = "#DD7285"
blue = "#939393"
magenta = "#AFAFAF"
cyan = "#E99B9B"
white = "#bfbfbf"

[colors.bright]
black = "#615050"
red = "#EE1F25"
green = "#CD3E46"
yellow = "#DD7285"
blue = "#939393"
magenta = "#AFAFAF"
cyan = "#E99B9B"
white = "#bfbfbf"

[colors.dim]
black = "#bfbfbf"
red = "#EE1F25"
green = "#AFAFAF"
yellow = "#DD7285"
blue = "#939393"
magenta = "#CD3E46"
cyan = "#E99B9B"
white = "#615050"

