--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/judas/wallpaper/gas-station.jpg"

-- Special
background="#011C22"
foreground="#bfc6c7"
cursor="#bfc6c7"

-- Colors
color0="#011C22"
color1="#536869"
color2="#965D70"
color3="#247094"
color4="#61929D"
color5="#92ABAA"
color6="#A8BAC1"
color7="#bfc6c7"
color8="#596a6e"
color9="#536869"
color10="#965D70"
color11="#247094"
color12="#61929D"
color13="#92ABAA"
color14="#A8BAC1"
color15="#bfc6c7"
