# Shell variables
# Generated by 'wal'
wallpaper="/home/judas/wallpaper/2.jpg"

# Special
background='#010101'
foreground='#bfbfbf'
cursor='#bfbfbf'

# Colors
color0='#010101'
color1='#EE1F25'
color2='#CD3E46'
color3='#DD7285'
color4='#939393'
color5='#AFAFAF'
color6='#E99B9B'
color7='#bfbfbf'
color8='#615050'
color9='#EE1F25'
color10='#CD3E46'
color11='#DD7285'
color12='#939393'
color13='#AFAFAF'
color14='#E99B9B'
color15='#bfbfbf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
