--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/judas/wallpaper/2.jpg"

-- Special
background="#010101"
foreground="#bfbfbf"
cursor="#bfbfbf"

-- Colors
color0="#010101"
color1="#EE1F25"
color2="#CD3E46"
color3="#DD7285"
color4="#939393"
color5="#AFAFAF"
color6="#E99B9B"
color7="#bfbfbf"
color8="#615050"
color9="#EE1F25"
color10="#CD3E46"
color11="#DD7285"
color12="#939393"
color13="#AFAFAF"
color14="#E99B9B"
color15="#bfbfbf"
